input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["app-logs"]
    codec => json
  }
}

filter {
  mutate {
    add_field => { "env" => "local" }
  }
}

output {
  stdout { codec => rubydebug }

  elasticsearch {
    hosts => ["http://13.206.85.172:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
}